// SimCare courses + avatars (scraped from catalog.simcare.ai, June 2026)

export const SIMCARE_COURSES = [
  {
    courseId: "intro-counseling",
    courseName: "Introduction to Counseling",
    courseUrl: "https://catalog.simcare.ai/introduction-to-counseling",
    description: "Foundational micro-skills course: empathy, active listening, open-ended questions, paraphrasing, reflection of feeling, unconditional positive regard, and introductory risk assessment.",
    simcare_cacrep_codes: ["2.B.5.f", "2.B.5.g", "2.B.5.h", "2.B.5.l"],
    cacrep_2024_codes: ["3.E.8", "3.E.9", "3.E.13", "3.E.19"],
    avatars: [
      { name: "Emma", age: 23, module: "Module 1", skill_focus: "Establishing Basic Empathy",
        presenting_problem: "Juvenile idiopathic arthritis, chronic pain, medical trauma, isolation",
        why_useful: "Practice validating physical and emotional pain without toxic positivity.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.9"] },
      { name: "Radha", age: 24, module: "Module 2", skill_focus: "Utilizing Open-Ended Questions",
        presenting_problem: "Anxiety, intrusive thoughts, avoidance, physical tension",
        why_useful: "Practice exclusively non-leading open-ended questions (Who/What/How).",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.9"] },
      { name: "Sandy", age: 43, module: "Module 3", skill_focus: "Paraphrasing and Summarizing",
        presenting_problem: "Disordered eating, body image issues, scarcity trauma",
        why_useful: "Practice structuring an overwhelming narrative through paraphrasing and summary.",
        simcare_cacrep: ["2.B.5.g", "2.B.5.h"], cacrep_2024: ["3.E.9", "3.E.13"] },
      { name: "Tracy", age: 46, module: "Module 4", skill_focus: "Reflection of Feeling",
        presenting_problem: "Anxiety, agoraphobia, shame, avoidance behavior",
        why_useful: "Practice accurately identifying and reflecting complex emotional states.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.9"] },
      { name: "Natalia", age: 39, module: "Module 5", skill_focus: "Unconditional Positive Regard",
        presenting_problem: "Extramarital affair, burnout, guilt, family conflict",
        why_useful: "Practice suspending moral judgment and maintaining genuine warmth.",
        simcare_cacrep: ["2.B.5.f"], cacrep_2024: ["3.E.8"] },
      { name: "Nate", age: 51, module: "Module 6", skill_focus: "Resisting the Righting Reflex",
        presenting_problem: "Profound grief, loss of both children, complicated bereavement",
        why_useful: "Practice sitting with silence and resisting the urge to fix.",
        simcare_cacrep: ["2.B.5.f", "2.B.5.g"], cacrep_2024: ["3.E.8", "3.E.9"] },
      { name: "Peter", age: 37, module: "Module 7", skill_focus: "Responding to Passive Suicidal Ideation",
        presenting_problem: "Professional burnout, isolation, passive suicidal ideation",
        why_useful: "Practice calm, introductory risk assessment questioning without panic.",
        simcare_cacrep: ["2.B.5.l"], cacrep_2024: ["3.E.19"] }
    ]
  },
  {
    courseId: "ethical-legal",
    courseName: "Ethical and Legal Issues in Counseling",
    courseUrl: "https://catalog.simcare.ai/ethical-and-legal-issues-in-counseling",
    description: "ACA Code of Ethics in practice: confidentiality, limits of confidentiality, dual relationships, scope of practice, mandated reporting, technology ethics, and duty to warn.",
    simcare_cacrep_codes: ["2.B.1.d", "2.B.1.e", "2.B.1.i", "2.B.5.b"],
    cacrep_2024_codes: ["3.A.10", "3.A.4", "3.A.5", "3.E.8"],
    avatars: [
      { name: "Roger", age: 68, module: "Module 1", skill_focus: "Scope of Practice and Ethical Referral",
        presenting_problem: "Cognitive decline, memory loss, family concern, stigma",
        why_useful: "Practice discussing limits of competence and initiating an ethical referral.",
        simcare_cacrep: ["2.B.1.d"], cacrep_2024: ["3.A.10"] },
      { name: "Eva", age: 15, module: "Module 2", skill_focus: "Confidentiality with Minors and Technology Ethics",
        presenting_problem: "School avoidance, alcohol use, parental surveillance via apps",
        why_useful: "Practice explaining confidentiality limits to a minor while addressing digital privacy.",
        simcare_cacrep: ["2.B.1.d", "2.B.1.i"], cacrep_2024: ["3.A.10", "3.A.5"] },
      { name: "Sarah", age: 32, module: "Module 3", skill_focus: "Dual Relationships and Boundary Setting",
        presenting_problem: "Loneliness, social isolation, requesting social friendship from counselor",
        why_useful: "Practice declining a dual relationship respectfully while preserving alliance.",
        simcare_cacrep: ["2.B.1.d"], cacrep_2024: ["3.A.10"] },
      { name: "AJ", age: 34, module: "Module 4", skill_focus: "Confidentiality with Mandated Clients",
        presenting_problem: "Court-mandated counseling, 14 months sobriety, resentful of system",
        why_useful: "Practice clearly explaining what is and is not shared with the court.",
        simcare_cacrep: ["2.B.1.d"], cacrep_2024: ["3.A.10"] },
      { name: "Maria", age: 24, module: "Module 5", skill_focus: "Ethical Bartering and Access Advocacy",
        presenting_problem: "Financial barriers to counseling, requesting bartering arrangement",
        why_useful: "Practice navigating ACA ethics on bartering while addressing systemic access barriers.",
        simcare_cacrep: ["2.B.1.d", "2.B.1.e"], cacrep_2024: ["3.A.10", "3.A.4"] },
      { name: "Derek", age: null, module: "Module 6", skill_focus: "Duty to Warn",
        presenting_problem: "Expressed intent to harm a specific third party, identifiable victim",
        why_useful: "Practice identifying the threshold for duty to warn and responding appropriately.",
        simcare_cacrep: ["2.B.1.d"], cacrep_2024: ["3.A.10", "3.G.13"] },
      { name: "Neha", age: 22, module: "Module 7", skill_focus: "Scope of Practice",
        presenting_problem: "Requesting EMDR from an untrained counselor, trauma history",
        why_useful: "Practice explaining scope of practice limitations while maintaining the alliance.",
        simcare_cacrep: ["2.B.1.d"], cacrep_2024: ["3.A.10"] }
    ]
  },
  {
    courseId: "case-conceptualization",
    courseName: "Case Conceptualization and Treatment Planning",
    courseUrl: "https://catalog.simcare.ai/case-conceptualization-and-treatment-planning",
    description: "Bridging assessment to treatment: building therapeutic alliance, applying theory to formulation, transdiagnostic conceptualization, multicultural treatment planning, and termination.",
    simcare_cacrep_codes: ["2.B.1.d", "2.B.5.f", "2.B.5.g"],
    cacrep_2024_codes: ["3.A.10", "3.E.2", "3.E.3", "3.E.8", "3.E.9", "3.E.13"],
    avatars: [
      { name: "Abe", age: 25, module: "Module 1", skill_focus: "Building Therapeutic Alliance Through Immediacy",
        presenting_problem: "Low mood, fatigue, self-criticism, first-time therapy client",
        why_useful: "Practice building alliance through immediacy and empathy with a hesitant client.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.9"] },
      { name: "Rosa", age: 45, module: "Module 2", skill_focus: "Applying Theory to Caregiver Burnout",
        presenting_problem: "Caregiver burnout, Alzheimer's mother, isolation, guilt",
        why_useful: "Practice introducing a specific counseling theory in layman's terms.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.1", "3.E.3"] },
      { name: "Miguel", age: 19, module: "Module 3", skill_focus: "Transdiagnostic Case Conceptualization",
        presenting_problem: "Social avoidance, extreme isolation, poor diet, physical decline",
        why_useful: "Practice transdiagnostic conceptualization looking beyond a single diagnosis.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.2", "3.E.3"] },
      { name: "Ethan", age: 31, module: "Module 4", skill_focus: "Collaborative CBT Treatment Planning",
        presenting_problem: "Compulsive behavior, missed deadlines, disrupted sleep",
        why_useful: "Practice collaborating with a client to revise a poorly written treatment plan.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.3", "3.E.13", "3.E.19"] },
      { name: "Devon", age: 19, module: "Module 5", skill_focus: "Multiculturally Competent Treatment Planning",
        presenting_problem: "Disordered eating, gender dysphoria, misgendering at home",
        why_useful: "Practice multicultural case conceptualization while exploring intersectional identity.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.B.1", "3.B.5", "3.E.3"] },
      { name: "Camila", age: 27, module: "Module 6", skill_focus: "Feminist Theory and Cultural Humility",
        presenting_problem: "Emotional abuse in arranged marriage, immigration, isolation",
        why_useful: "Practice cultural humility and feminist theory perspectives in formulation.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.B.2", "3.B.3", "3.E.3"] },
      { name: "Kenneth", age: null, module: "Module 7", skill_focus: "Termination and Treatment Review",
        presenting_problem: "Completing treatment after working through family-of-origin issues",
        why_useful: "Practice processing termination, reviewing treatment goals, and consolidating gains.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.9", "3.E.13"] }
    ]
  },
  {
    courseId: "counseling-theories",
    courseName: "Counseling Theory and Techniques",
    courseUrl: "https://catalog.simcare.ai/counseling-theory-and-techniques",
    description: "Application of major theoretical frameworks: psychodynamic, gestalt, CBT, existential, REBT, narrative, DBT, and person-centered therapy.",
    simcare_cacrep_codes: ["3.E.1", "3.E.2", "3.E.3", "3.E.5", "3.E.9"],
    cacrep_2024_codes: ["3.E.1", "3.E.2", "3.E.3", "3.E.10", "3.E.15", "3.E.21"],
    avatars: [
      { name: "Ingrid", age: null, module: "Module 1", skill_focus: "Psychodynamic Theory — Defense Mechanisms",
        presenting_problem: "Complicated grief, intellectualization and compartmentalization defenses",
        why_useful: "Practice gently bypassing cognitive defenses to reach underlying emotion.",
        simcare_cacrep: ["3.E.1", "3.E.2"], cacrep_2024: ["3.E.1", "3.E.2"] },
      { name: "Mei", age: null, module: "Module 2", skill_focus: "Gestalt Therapy — Empty Chair Technique",
        presenting_problem: "Sibling grief, guilt, unfinished business, compulsive caregiving",
        why_useful: "Practice introducing and facilitating the gestalt empty chair technique.",
        simcare_cacrep: ["3.E.1"], cacrep_2024: ["3.E.1", "3.E.10"] },
      { name: "Caroline", age: null, module: "Module 3", skill_focus: "CBT — Socratic Questioning",
        presenting_problem: "Self-blame and guilt following spouse's suicide, suicidal ideation",
        why_useful: "Practice using Socratic questioning to gently challenge an unhelpful cognition.",
        simcare_cacrep: ["3.E.1", "3.E.2", "3.E.5"], cacrep_2024: ["3.E.1", "3.E.2", "3.E.15"] },
      { name: "Tamera", age: null, module: "Module 4", skill_focus: "Existential Therapy — Meaning and Isolation",
        presenting_problem: "Caregiver burnout, loss of identity, existential isolation",
        why_useful: "Practice applying existential concepts around meaning-making and isolation.",
        simcare_cacrep: ["3.E.1"], cacrep_2024: ["3.E.1"] },
      { name: "Joe", age: 40, module: "Module 5", skill_focus: "REBT — Disputing Irrational Beliefs",
        presenting_problem: "Job loss in mining industry, masculine identity tied to work",
        why_useful: "Practice applying the REBT ABC model to identify and dispute irrational beliefs.",
        simcare_cacrep: ["3.E.1", "3.E.3"], cacrep_2024: ["3.E.1", "3.E.3"] },
      { name: "Helen", age: null, module: "Module 6", skill_focus: "Narrative Therapy — Externalizing the Problem",
        presenting_problem: "Retirement identity crisis, relocation grief, loss of social role",
        why_useful: "Practice externalizing the client's feeling of irrelevance.",
        simcare_cacrep: ["3.E.1", "3.E.3"], cacrep_2024: ["3.E.1", "3.E.3"] },
      { name: "Serena", age: null, module: "Module 7", skill_focus: "DBT — Distress Tolerance Skills",
        presenting_problem: "Combat PTSD, hypervigilance, alcohol use to cope, disrupted sleep",
        why_useful: "Practice applying DBT distress tolerance skills before trauma processing.",
        simcare_cacrep: ["3.E.1", "3.E.5"], cacrep_2024: ["3.E.1", "3.E.15"] },
      { name: "Tyler", age: null, module: "Module 8", skill_focus: "Person-Centered Therapy — Core Conditions",
        presenting_problem: "Bullying, academic failure, refugee family pressure",
        why_useful: "Practice establishing unconditional positive regard, empathy, and congruence.",
        simcare_cacrep: ["3.E.1", "3.E.9"], cacrep_2024: ["3.E.1", "3.E.21"] }
    ]
  },
  {
    courseId: "multicultural",
    courseName: "Multicultural Counseling",
    courseUrl: "https://catalog.simcare.ai/multicultural-counseling",
    description: "Social, cultural, and systemic factors shaping identity: minority stress, intersectionality, acculturation, institutional betrayal, indigenous worldviews, and affirming counseling.",
    simcare_cacrep_codes: ["3.B.1", "3.B.2", "3.B.3", "3.B.5"],
    cacrep_2024_codes: ["3.B.1", "3.B.2", "3.B.3", "3.B.5"],
    avatars: [
      { name: "Camila", age: null, module: "Module 1", skill_focus: "Cultural Formulation Without Pathologizing",
        presenting_problem: "Latina immigrant in coercive marriage, fears counseling will betray family",
        why_useful: "Practice cultural formulation: acknowledging cultural context without pathologizing.",
        simcare_cacrep: ["3.B.2"], cacrep_2024: ["3.B.2"] },
      { name: "Leroy", age: null, module: "Module 2", skill_focus: "Brokering Trust After Institutional Betrayal",
        presenting_problem: "Black Army veteran mandated to counseling after suspected racial profiling",
        why_useful: "Practice validating racial profiling and institutional betrayal experiences.",
        simcare_cacrep: ["3.B.5"], cacrep_2024: ["3.B.5"] },
      { name: "Devon", age: null, module: "Module 3", skill_focus: "Navigating Intersectional Minority Stress",
        presenting_problem: "Black nonbinary student, disordered eating, gender dysphoria, family rejection",
        why_useful: "Practice creating culturally affirming space for intersectional identity.",
        simcare_cacrep: ["3.B.1", "3.B.5"], cacrep_2024: ["3.B.1", "3.B.5"] },
      { name: "Bob", age: null, module: "Module 4", skill_focus: "Honoring Indigenous Worldviews in Addiction Treatment",
        presenting_problem: "Diné man with opioid use following workplace injury",
        why_useful: "Practice exploring historical mistrust of Western medicine while honoring indigenous worldview.",
        simcare_cacrep: ["3.B.3"], cacrep_2024: ["3.B.3"] },
      { name: "Maria", age: null, module: "Module 5", skill_focus: "Differentiating Familismo from Clinical Anxiety",
        presenting_problem: "Second-generation Mexican-American mother, hyper-vigilance about family",
        why_useful: "Practice cultural bridging: differentiating culturally held values from clinical anxiety.",
        simcare_cacrep: ["3.B.2"], cacrep_2024: ["3.B.2"] },
      { name: "Ahmed", age: null, module: "Module 6", skill_focus: "Addressing Acculturative Stress and Collectivist Shame",
        presenting_problem: "International student from Saudi Arabia, academic struggle, family shame",
        why_useful: "Practice normalizing acculturative stress and reframing mental health within a collectivist frame.",
        simcare_cacrep: ["3.B.2", "3.B.3"], cacrep_2024: ["3.B.2", "3.B.3"] },
      { name: "Maya", age: 16, module: "Module 7", skill_focus: "Affirming Identity Amidst Systemic Hostility",
        presenting_problem: "African-American transgender girl, severe bullying, family rejection",
        why_useful: "Practice actively affirming trans identity while validating systemic hostility.",
        simcare_cacrep: ["3.B.1", "3.B.5"], cacrep_2024: ["3.B.1", "3.B.5"] }
    ]
  },
  {
    courseId: "career-counseling",
    courseName: "Career Counseling",
    courseUrl: "https://catalog.simcare.ai/career-counseling",
    description: "Career development theories, career transitions, systemic barriers, family pressure, career grief, and goal setting with resistant clients.",
    simcare_cacrep_codes: ["2.D.1.b", "2.D.1.d", "2.D.1.e", "2.D.1.g"],
    cacrep_2024_codes: ["3.D.1", "3.D.2", "3.D.5"],
    avatars: [
      { name: "Valentina", age: 55, module: "Module 1", skill_focus: "Empathy with Immigrant Underemployment",
        presenting_problem: "Former lead engineer from Russia, now working as delivery driver",
        why_useful: "Practice high-level empathy while navigating a blunt, authority-distrustful client.",
        simcare_cacrep: ["2.D.1.b", "2.D.1.d"], cacrep_2024: ["3.D.2"] },
      { name: "Anna", age: 19, module: "Module 2", skill_focus: "Career Indecision and Family Pressure",
        presenting_problem: "Sophomore with panic symptoms about major declaration, family pressure",
        why_useful: "Practice helping a student identify factors contributing to career indecision.",
        simcare_cacrep: ["2.D.1.b"], cacrep_2024: ["3.D.1", "3.D.2"] },
      { name: "Isabel", age: 21, module: "Module 3", skill_focus: "Open-Ended Questions in Career Counseling",
        presenting_problem: "First-generation college student, decision paralysis",
        why_useful: "Practice strictly using expansive non-leading open-ended questions in career work.",
        simcare_cacrep: ["2.D.1.e"], cacrep_2024: ["3.D.2"] },
      { name: "Evan", age: 24, module: "Module 4", skill_focus: "Goal Setting with Apathetic Client",
        presenting_problem: "Recent graduate attending counseling only due to parent pressure",
        why_useful: "Practice breaking through resistance, validating frustration, and setting modest goals.",
        simcare_cacrep: ["2.D.1.g"], cacrep_2024: ["3.D.1"] },
      { name: "Donna", age: 52, module: "Module 5", skill_focus: "Career Identity Loss and Medical Retirement",
        presenting_problem: "Former airline purser forced into early medical retirement",
        why_useful: "Practice providing deep empathy for career grief without trying to fix it.",
        simcare_cacrep: ["2.D.1.b"], cacrep_2024: ["3.D.2"] }
    ]
  },
  {
    courseId: "substance-use",
    courseName: "Substance Use and Addiction",
    courseUrl: "https://catalog.simcare.ai/substance-abuse-and-addiction",
    description: "Motivational Interviewing (OARS, PACE, rolling with resistance, elicit-provide-elicit, confidence ruler), confidentiality with minors, and addiction-context risk assessment.",
    simcare_cacrep_codes: ["2.B.3.d", "2.B.5.f", "2.B.5.g", "2.B.1.d"],
    cacrep_2024_codes: ["3.C.5", "3.E.8", "3.E.9", "3.E.15", "3.A.10", "3.E.19"],
    avatars: [
      { name: "Dylan", age: 17, module: "Module 1", skill_focus: "Confidentiality with Minor and Substance Use",
        presenting_problem: "High-achieving teenager in panic after drinking and underage party",
        why_useful: "Practice de-escalating acute anxiety and clearly explaining confidentiality limits.",
        simcare_cacrep: ["2.B.1.d"], cacrep_2024: ["3.A.10"] },
      { name: "Bob", age: 32, module: "Module 2", skill_focus: "MI Spirit — PACE with Resistant Client",
        presenting_problem: "Former construction foreman with opioid dependency, resistant to treatment",
        why_useful: "Practice Motivational Interviewing PACE (Partnership, Acceptance, Compassion, Evocation).",
        simcare_cacrep: ["2.B.5.f", "2.B.5.g"], cacrep_2024: ["3.E.8", "3.E.9", "3.E.15"] },
      { name: "Reid", age: 20, module: "Module 3", skill_focus: "OARS with Suicidal Ideation in Addiction Context",
        presenting_problem: "Transgender man, recent job loss due to drinking, passive suicidal ideation",
        why_useful: "Practice using OARS skills to stay grounded in a client's experience while assessing risk.",
        simcare_cacrep: ["2.B.5.g", "2.B.5.l"], cacrep_2024: ["3.E.9", "3.E.19"] },
      { name: "Luis", age: 37, module: "Module 4", skill_focus: "Mandated Client Goal Setting Using Scaling Questions",
        presenting_problem: "DUI-mandated counseling, views counselor as extension of court",
        why_useful: "Practice balancing confidentiality limits explanation with relational engagement.",
        simcare_cacrep: ["2.B.1.d", "2.B.5.g"], cacrep_2024: ["3.A.10", "3.E.9", "3.E.15"] },
      { name: "Mike", age: 34, module: "Module 5", skill_focus: "Rolling with Resistance — Cannabis Ambivalence",
        presenting_problem: "High school teacher using cannabis for burnout management, ambivalent",
        why_useful: "Practice rolling with resistance by actively avoiding the righting reflex.",
        simcare_cacrep: ["2.B.5.f", "2.B.5.g"], cacrep_2024: ["3.E.8", "3.E.15"] },
      { name: "Marna", age: 78, module: "Module 6", skill_focus: "Elicit-Provide-Elicit with Older Adult",
        presenting_problem: "Widowed older adult mixing prescription medication and alcohol",
        why_useful: "Practice the MI Elicit-Provide-Elicit skill to explore perceptions before sharing information.",
        simcare_cacrep: ["2.B.5.g"], cacrep_2024: ["3.E.9", "3.E.15"] },
      { name: "Rami", age: 29, module: "Module 7", skill_focus: "MI Confidence Ruler with Process Addiction",
        presenting_problem: "MSW student, paralyzed by fear of failure after drinking relapse and gambling",
        why_useful: "Practice using the MI Confidence Ruler to shift focus from importance to change capability.",
        simcare_cacrep: ["2.B.3.d", "2.B.5.g"], cacrep_2024: ["3.C.5", "3.E.9", "3.E.15"] }
    ]
  },
  {
    courseId: "marriage-family",
    courseName: "Marriage, Couple and Family Counseling",
    courseUrl: "https://catalog.simcare.ai/marriage-couple-and-family-counseling",
    description: "Systemic counseling: EFT pursue/withdraw cycles, betrayal trauma, Gottman softened startup, family-of-origin work, sexual desire discrepancy, and polyamorous systems.",
    simcare_cacrep_codes: ["5.F.1.f", "5.F.2.g", "5.F.2.m", "5.F.3.h"],
    cacrep_2024_codes: ["3.E.1", "3.C.1"],
    avatars: [
      { name: "Brian and Jordan", age: null, module: "Module 1", skill_focus: "Staying Present with High Emotional Intensity",
        presenting_problem: "Couple argument escalating around disconnection and unmet needs",
        why_useful: "Practice staying emotionally present without rushing to calm or solve.",
        simcare_cacrep: ["5.F.2.g"], cacrep_2024: ["3.E.1"] },
      { name: "Aisha", age: 22, module: "Module 2", skill_focus: "Family-of-Origin Systems and Resistance to Problem-Solving",
        presenting_problem: "College senior, disconnected from business degree, family expectations",
        why_useful: "Practice resisting the urge to problem-solve and instead using systemic exploration.",
        simcare_cacrep: ["5.F.2.m"], cacrep_2024: ["3.E.1", "3.C.1"] },
      { name: "Lena and Mark", age: null, module: "Module 3", skill_focus: "EFT — Pursue/Withdraw Cycle",
        presenting_problem: "Couple escalating over small things, pursue/withdraw dynamic",
        why_useful: "Practice reflecting not just content but deeper meaning, slowing the cycle.",
        simcare_cacrep: ["5.F.1.f", "5.F.2.g"], cacrep_2024: ["3.E.1"] },
      { name: "Dana and Sarah", age: null, module: "Module 4", skill_focus: "Gottman Method — Softened Startup",
        presenting_problem: "Same-sex couple, frequent arguments escalating with criticism",
        why_useful: "Practice gently interrupting criticism and coaching clients toward softened startup.",
        simcare_cacrep: ["5.F.2.g"], cacrep_2024: ["3.E.1"] },
      { name: "Elise and Jared", age: null, module: "Module 5", skill_focus: "Betrayal Trauma in Couples",
        presenting_problem: "Interracial couple, aftermath of two-year emotional affair",
        why_useful: "Practice centering the betrayed partner's experience while holding space for both.",
        simcare_cacrep: ["5.F.1.f"], cacrep_2024: ["3.E.1"] },
      { name: "Alex, Priya, and Mateo", age: null, module: "Module 6", skill_focus: "Systemic Tracking in Polyamorous Triad",
        presenting_problem: "Closed triad, Priya feeling excluded as Alex and Mateo bond",
        why_useful: "Practice reflecting feelings, naming triangulation, and helping a triad track systemically.",
        simcare_cacrep: ["5.F.2.m"], cacrep_2024: ["3.E.1"] },
      { name: "Anne and Sajan", age: null, module: "Module 7", skill_focus: "Working with Sexual Desire Discrepancy",
        presenting_problem: "Married couple, desire discrepancy, Anne feeling unwanted",
        why_useful: "Practice holding space for intimacy conversations, connecting desire to attachment.",
        simcare_cacrep: ["5.F.3.h"], cacrep_2024: ["3.E.1"] }
    ]
  }
];
